# Generated by Django 4.0.3 on 2022-06-23 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_customer_password_alter_sign_up_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart_id',
        ),
    ]
